[build]
builder = "DOCKERFILE"
dockerfile = "backend/Dockerfile"
rootDirectory = "backend"

[deploy]
startCommand = "python entrypoint.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
